[FEATURE] Error 4xx | 5xx does not allow parsing message returned backend
pliplox/MascotApp pull request #17
Opened 2020-10-22 22:37 UTC by MatiasBarrera

- Interceptor is added for response
- changes to login and registration in context and respective screens

note: this pr skips tests (singin.test.js) because will be implemented in the next card... i promise

2020-10-22 23:18 UTC, alexanderbarrosorellana commented on package.json
> +      "./node_modules/react-native-gesture-handler/jestSetup.js"
???

2020-10-22 23:26 UTC, alexanderbarrosorellana requested changes
buen trabajo bro, van dudas, cambios y comentarios

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +        setErrorMessage('');
esto es innecesario pq ya se inicializa el state en ''

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +        setErrorMessage('');
o el estado de error queda guardado si hay un error y posteriormente no?

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +        setErrorMessage('');
lo mismo, de la inicialización del state, errorMessage ya debe ser un string vacío a menos que pase lo que dije en el comentario anterior

...el else esta muy pegado a la llave

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> -      await signIn('admin@pliplox.com', '123123');
jasdjjasd perdon XD

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +  const handleNavigationToSignup = () => {
si es camelcaess el up deberia tener mayuscula Up

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +    setErrorMessage('')
es raro que esto esté aqui, por que?

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignUp.test.js
> +        const { post } = mascotappiMock;
quitar espacios extra

2020-10-22 23:26 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignUp.test.js
no pasa este test aun? :c

2020-10-22 23:28 UTC, alexanderbarrosorellana commented on package.json
> +      "./node_modules/react-native-gesture-handler/jestSetup.js"
eliminar espacio extra

2020-10-22 23:32 UTC, MatiasBarrera commented on src/context/AuthContext.js
> +        setErrorMessage('');
si por ejemplo intentas logear y te aparece el msg XXXX luego vas a register (que tambien utiliza el errorMessage) mostrara el mismo error

2020-10-22 23:33 UTC, MatiasBarrera commented on src/context/AuthContext.js
> +        setErrorMessage('');
por eso cuando navegas o te logras registrar o iniciar sesion lo seteo por defecto

2020-10-22 23:35 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +        setErrorMessage('');
✅

2020-10-22 23:35 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
>        // signIn(email, password);
eliminar este comentario pls

2020-10-22 23:55 UTC, MatiasBarrera commented on src/screens/auth/SignIn.js
> +    setErrorMessage('')
que cosa ? la funcion ? si es eso antes se llamaba directamente en el boton pero no me gusta asi xD.. prefiero crearla.

si es por el setErrorMessage... es para que no se vea el msg de login en register.

2020-10-22 23:55 UTC, MatiasBarrera commented on src/screens/auth/__tests__/SignUp.test.js
no entiendo como funciona la verdad... XD

2020-10-23 00:13 UTC, alexanderbarrosorellana approved these changes

2020-10-23 00:39 UTC, merged