[FEATURE] Modify Signin design
pliplox/MascotApp pull request #20
Opened 2020-11-17 01:55 UTC by MatiasBarrera

- Design change is made according to mockup
- Snackbar is added to display error messages
- More settings are added for the Spanish and English languages
- Loading icon inside the button when wait response
- Tests

**Note:** Only the renders of the controls is tested and little else 👎

2020-11-19 23:09 UTC, alexanderbarrosorellana requested changes
Mitad preguntas y mitad cambios, por lo general, bien!

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on App.js
> +                headerShown: false,
que es esto y por que?

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on debug.log
> +[1022/232754.422:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
emmm este archivo creo que no deberia estar, si no esta en el .git ignore, agregarlo

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/images/index.js
> +export const patitas = require('./patitas.png');
traducir nombre de archivos y exportación a inglés

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/lang/en.json
> +        "withoutAccount": "You do not have an account?"
cambiar por 
```
Don't have an account?
```

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +        ShowSnackBar(`\u{1F625} ${message}`);
para que es el código?

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +        colors={['#390350', '#3a0252', '#52007c', '#3a0252', '#390350']}>
agregar colores como constantes mas arriba, antes de definir el componente y despues llamarlos, algo como:
```js 
const COLORS = { green: 'green_hex', red: 'red_rgba' };
const { green, red } = COLORS;

// Usarlo en el componente asi: 
colors ={[ green, red ]}

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +              justifyContent: 'space-between',
usar `StyleSheet`

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +    backgroundColor: '#390350',
agregar color al theme y llamarlo de ahi

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +    backgroundColor: '#6066af',
agregar color al theme y llamarlo de ahi

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +    backgroundColor: '#6066af',
agregar color al theme y llamarlo de ahi

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignIn.test.js
> +        wrapper.debug();
eliminar debug

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignIn.test.js
> +        /**TODO: No funca... pendiente */
traducir todo al inglés

2020-11-19 23:09 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignIn.test.js
> +        /**Fin todo */
traducir

2020-11-19 23:25 UTC, MatiasBarrera commented on App.js
> +                headerShown: false,
para que no se vea la cabecera

2020-11-19 23:27 UTC, MatiasBarrera commented on src/screens/auth/SignIn.js
> +        ShowSnackBar(`\u{1F625} ${message}`);
Es una cara triste como en la App de Fintual

2020-11-20 00:03 UTC, MatiasBarrera commented on src/screens/auth/SignIn.js
> +        ShowSnackBar(`\u{1F625} ${message}`);
![image](https://user-images.githubusercontent.com/38894536/99739022-9a82c380-2aaa-11eb-8c3e-7ed7a8f3e88b.png)

2020-11-20 00:10 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +        ShowSnackBar(`\u{1F625} ${message}`);
buenisimo, agregalo como constante arribita porfis, algo como:
```js
const EMOJI = { sad_face: 'whatevercode' }

2020-11-20 00:10 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +        ShowSnackBar(`\u{1F625} ${message}`);
o en verdad la key en camelCase en vez de snake_case

2020-11-20 11:56 UTC, alexanderbarrosorellana commented on src/components/AuthLayout.js
> +};
deben estar en `camelCase`, ahora estan en `PascalCase`

2020-11-20 11:57 UTC, alexanderbarrosorellana commented on emojis.js
> +export default emojis;
very nice

2020-11-20 11:57 UTC, alexanderbarrosorellana commented on src/screens/auth/SignIn.js
> +      backgroundColor: 'rgba(96, 102, 175, 0.90)',
pq se cambió esto? 👀

2020-11-20 16:57 UTC, MatiasBarrera commented on src/screens/auth/SignIn.js
> +      backgroundColor: 'rgba(96, 102, 175, 0.90)',
mi intencion era que el snackbar tuviera el mismo color que los botones y antes no lo tenia XD ahora si jijij... es sutil el cambio xD

2020-11-24 14:10 UTC, alexanderbarrosorellana commented on debug.log
> +[1022/232754.422:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
👀

2020-11-25 20:20 UTC, alexanderbarrosorellana approved these changes
🐳

2020-11-25 21:01 UTC, merged