[FEATURE] Modified SignUp design
pliplox/MascotApp pull request #22
Opened 2020-12-10 00:24 UTC by MatiasBarrera

- Design change is made according to mockup
- Reusable components are created for the authentication screens
- Snackbar is added to display error messages
- More settings are added for the Spanish and English languages
- Loading icon inside the button when wait response
- Tests

Note: Only the renders of the controls are tested and little else... I failed :(

2020-12-10 22:56 UTC, alexanderbarrosorellana requested changes
Nice job dude, van solicitudes de cambio 🧸

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/SnackBar.js
> +export const ShowSnackBar = props => {
aquie sería mejor hacer que props sea destructurado apenas llegan ({ message, backgroundColor });

y definir abajo ShowSnackBar.propTypes = {}...
por ahi debe haber un ejemplo

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/SnackBar.js
> +export const ShowSnackBar = props => {
y ShowSnackBar.defaultProps si es necesario

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/SnackBar.js
> +};
esto esta extraño, al ser una función que hace algo, en vez que sea un componente, lo exportaría como camelCase, onda `export const dismissSnackBar = ()...`

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/Avatar.js
> +const Avatar = props => {
aqui lo mismo con la destructuración `{(style, avatar)} = {...` y con los las Avatar.propType...

y que la prop se llame avatar y que el componente se llame igual es confuso

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/Avatar.js
> +    <>
este wrapper deberia ser innecesario `<></>`, pq es un solo componente

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/FooterImages.js
> +const FooterImages = props => {
destructurar props cuando llegan y usar propTypes

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/OtherAccess.js
> +        {label || 'Label'}
esto va a llegar como el string `Label` supongo que no esta bien

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/OtherAccess.js
> +        <View style={{ flex: 1 }}>
preferir createStyleSheet en vez de inline style

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/OtherAccess.js
> +            style={googleStyle || [styles.btnOtherAcces, { marginEnd: 5 }]}>
agregar al styleSheet

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/components/auth/index.js
> +export { default as OtherAccess } from './OtherAccess';
bacan, un index pa los compoenentes! 👨🏽‍🎤

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/SignUp.js
> +          style={[styles.button, { marginTop: 10 }]}
agregar al StyleSheet

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/SignUp.js
> +          style={[styles.input, { marginBottom: 10 }]}
Agregar al StyleSheet

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/SignUp.js
> +          style={[styles.input, { marginBottom: 10 }]}
agregar al StyleSheet

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/SignUp.js
> +  const renderIcon = props => (
aprovechar de cambiar este nombre, ponerle como showPasswordIcon

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/SignUp.js
> +const themedStyles = StyleService.create({
si cambiaste esto, en las partes donde estas llamando a  `style={styles.algo}}` styles va a ser `undefined`, por lo tanto "algo", tambien va a ser `undefined`, tienes que cambiar todos los `style={styles.algo}}` por `style={themedStyle.algo}`

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignIn.test.js
> +    cleanup();
prueba sacandole el cleanup(), segun lo que he leido ya no es necesario en los tests

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignUp.test.js
> +    cleanup();
lo mismo, porfa trata de ver si aun es necesario el cleanup()

2020-12-10 22:56 UTC, alexanderbarrosorellana commented on src/screens/auth/__tests__/SignUp.test.js
> -        // all subscriptions and asynchronous tasks...
este warning ya no pasa?

2020-12-15 01:20 UTC, MatiasBarrera commented on src/screens/auth/__tests__/SignUp.test.js
> -        // all subscriptions and asynchronous tasks...
no estoy seguro... lo dejo por si acaso.

2020-12-15 01:34 UTC, MatiasBarrera commented on src/screens/auth/SignUp.js
> +const themedStyles = StyleService.create({
mmm line 26:
`const styles = useStyleSheet(themedStyles);`
nunca es undefined styles

2020-12-15 01:37 UTC, MatiasBarrera commented on src/components/auth/OtherAccess.js
> +        {label || 'Label'}
lo puse para evitar poner un texto random cuando maqueteo la cosa... asi veo el valor por defecto no mas.  Cosas de aspx XD. Lo quite.

2020-12-15 02:20 UTC, alexanderbarrosorellana approved these changes

2020-12-15 13:42 UTC, merged