[FEATURE] Add Splash
pliplox/MascotApp pull request #23
Opened 2020-12-18 01:53 UTC by MatiasBarrera

- Splash.js screen is added
- Modify useEffect & signOut in AuthContext.js
- Test App.js

2020-12-18 03:13 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> -      setLoadingUser(false);
estos loading pq se borran?

2020-12-18 03:14 UTC, alexanderbarrosorellana requested changes
Me queda una duda general, cuando puse el splash, lo puse como se me ocurrió... no leí en ninguna parte si asi se usa o no. Que opinas?

2020-12-18 03:14 UTC, alexanderbarrosorellana commented on src/screens/Splash.js
> +};
estos colores ya los he visto antes? si es así, llevar a un archivo aparte o agregarlos al theme

2020-12-18 03:19 UTC, MatiasBarrera commented on src/context/AuthContext.js
> -      setLoadingUser(false);
no son necesarios...al cerrar sesion aparece el splash y queda mal

2020-12-18 12:42 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> -      setLoadingUser(false);
yap, entonces verificar que cuando se llame a signOut en otras partes, el loadingUser no se esté usando, pq eso se usa para settear el spinner en el boton de cerrar sesión

2020-12-18 12:44 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> -      setLoadingUser(false);
por ej aquí https://github.com/pliplox/MascotApp/blob/c8854e11cd291f2796288744a2106d3835b3b930/src/screens/Home.js#L192

2020-12-24 02:48 UTC, alexanderbarrosorellana commented on __tests__/App.test.js
> +import "react-native";
que onda? el linter te lo cambió a doble comillas?, pta no debería 👀 , que te dice el warning o error?

2020-12-24 02:49 UTC, alexanderbarrosorellana commented on src/components/Gradient.js
> +  children: PropTypes.object && PropTypes.node.isRequired,
aqui solo con `node` esta bien

2020-12-24 18:59 UTC, alexanderbarrosorellana commented on .gitignore
> +.prettierrc
esto deberíamos resolverlo de otra forma, por ahora que pase, pero hay que solucionar

2020-12-24 19:00 UTC, alexanderbarrosorellana approved these changes

2020-12-24 19:09 UTC, merged