[FEATURE] Add Pet
pliplox/MascotApp pull request #24
Opened 2020-12-20 05:24 UTC by alexanderbarrosorellana

- Modify the linter implementation
- Change initial screen to  be Groups
- Update Gradle
- Modify axios interceptor
- List pets and users in group cards
- Add Create Pet screen
- Add MockedNavigator to testing utils

 ### To accomplish a smoother flow while creating a group or/and a pet, also it is to maintain some conventions by using the linter 

>NOTE: sorry to my reviewer because there are too many changes that are just semicolon ( ; ) removals

2020-12-20 16:26 UTC, MatiasBarrera requested changes
🚀 Nice job... unas observaciones por ahi 👀

2020-12-20 16:26 UTC, MatiasBarrera commented on src/components/group-card/MemberList.js
>  // import ButtonAccesory from './ButtonAccessory';
Quitar? o no?

2020-12-20 16:26 UTC, MatiasBarrera commented on src/lang/es.json
> +    "empty": "Todavía no hay grupos, puedes crear uno persionando el botón de abajo",
"persionando"

2020-12-20 16:26 UTC, MatiasBarrera commented on src/lang/es.json
> +    "error": "Algo salió mal, intenta mas tarde o contáctate con nosotros",
en vez de "contáctate con nosotros" creo que suena mejor  "contáctanos"

2020-12-20 16:26 UTC, MatiasBarrera commented on src/screens/groups/GroupList.js
> +      {/* Temporary button to sign out, this should be removed with bottom navigation implementation */}
En un "//TODO:" o "//FIXME:" (?)

2020-12-22 03:07 UTC, alexanderbarrosorellana commented on src/components/group-card/MemberList.js
>  // import ButtonAccesory from './ButtonAccessory';
no, es por el comentario de abajo, copy pastearé

2020-12-23 23:09 UTC, MatiasBarrera approved these changes
🐰

2020-12-23 23:09 UTC, merged