[FEATURE] Connect login with Facebook
pliplox/MascotApp pull request #36
Opened 2021-02-13 20:42 UTC by MatiasBarrera

- Added facebook signin with its logic

**Summary**
Add a new way to log in with Facebook credentials, to make logging easier, and enable the OtherAccess component with both logins (Google and Facebook).

> Note: Tests only rendered controls

2021-02-15 00:07 UTC, alexanderbarrosorellana requested changes

2021-02-15 00:07 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +   * @param {string} eccessToken
eccess

2021-02-15 00:07 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +    try {
creo que falta loading en alguna parte... hay feedback de cuando está cargando?

2021-02-15 00:07 UTC, alexanderbarrosorellana commented on src/screens/auth/FacebookSignin.js
> +    LoginManager.logInWithPermissions(['public_profile']).then(
no se puede usar await mejor, en vez de `then`?

2021-02-15 00:07 UTC, alexanderbarrosorellana commented on src/screens/auth/FacebookSignin.js
> +      async function (result) {
usar  arrow function mejor

2021-02-15 00:07 UTC, alexanderbarrosorellana commented on src/screens/auth/FacebookSignin.js
> +        console.error('Login fail with error: ' + error)
cual??

2021-02-15 02:09 UTC, MatiasBarrera commented on src/screens/auth/FacebookSignin.js
> +        console.error('Login fail with error: ' + error)
no lo se... no pude hacer que fallara.

2021-02-15 02:10 UTC, MatiasBarrera commented on src/context/AuthContext.js
> +    try {
cuando carga para la pagina de facebook? si es eso facebook ya lo tiene.

2021-02-15 04:13 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +    try {
nop, nuestro usuario

2021-02-15 04:14 UTC, alexanderbarrosorellana commented on src/screens/auth/FacebookSignin.js
> +        console.error('Login fail with error: ' + error)
me refiero a que el log es poco descriptivo, `login with facebook...`

2021-02-15 16:12 UTC, MatiasBarrera commented on src/context/AuthContext.js
> +    try {
mmm no solo se deshabilita el boton... ok en ese caso habra que agregar uno para google tambien

2021-02-15 17:16 UTC, alexanderbarrosorellana commented on src/context/AuthContext.js
> +    try {
eso lo estoy tomando no problem

2021-02-18 22:42 UTC, alexanderbarrosorellana approved these changes

2021-02-26 00:15 UTC, merged